N = int(input())
A, B = input().split()
A, B = map(int, input().split())
A_list = list(map(int, input().split()))
A_list = [input() for _ in range(N)]
A_lists = [list(input()) for _ in range(N)]
A_lists = [list(map(int, input().split())) for _ in range(N)]
S = input().strip()
S_list = list(input())
